@BazaarScanner_HostAddress = https://localhost:7102

GET {{BazaarScanner_HostAddress}}/api/items
Accept: application/json

###

POST {{BazaarScanner_HostAddress}}/api/items
Content-Type: application/json

{
  "name": "test3",
  "type": 1,
  "count": 1,
  "imageUrl": "https://example.com/test3.jpg"
}